// Code generated by MockGen. DO NOT EDIT.
// Source: internal/weather/repository.go
//
// Generated by this command:
//
//	mockgen -source=internal/weather/repository.go -destination=internal/weather/mock/repository_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockRepository is a mock of Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
	isgomock struct{}
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// GetWeatherByLocation mocks base method.
func (m *MockRepository) GetWeatherByLocation(ctx context.Context, location string) (float32, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetWeatherByLocation", ctx, location)
	ret0, _ := ret[0].(float32)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetWeatherByLocation indicates an expected call of GetWeatherByLocation.
func (mr *MockRepositoryMockRecorder) GetWeatherByLocation(ctx, location any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetWeatherByLocation", reflect.TypeOf((*MockRepository)(nil).GetWeatherByLocation), ctx, location)
}
