// Code generated by MockGen. DO NOT EDIT.
// Source: internal/weather/service.go
//
// Generated by this command:
//
//	mockgen -source=internal/weather/service.go -destination=internal/weather/mock/service_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	model "weather-api/internal/weather/model"

	gomock "go.uber.org/mock/gomock"
)

// MockService is a mock of Service interface.
type MockService struct {
	ctrl     *gomock.Controller
	recorder *MockServiceMockRecorder
	isgomock struct{}
}

// MockServiceMockRecorder is the mock recorder for MockService.
type MockServiceMockRecorder struct {
	mock *MockService
}

// NewMockService creates a new mock instance.
func NewMockService(ctrl *gomock.Controller) *MockService {
	mock := &MockService{ctrl: ctrl}
	mock.recorder = &MockServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockService) EXPECT() *MockServiceMockRecorder {
	return m.recorder
}

// GetWeatherByLocation mocks base method.
func (m *MockService) GetWeatherByLocation(ctx context.Context, location string) (*model.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetWeatherByLocation", ctx, location)
	ret0, _ := ret[0].(*model.Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetWeatherByLocation indicates an expected call of GetWeatherByLocation.
func (mr *MockServiceMockRecorder) GetWeatherByLocation(ctx, location any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetWeatherByLocation", reflect.TypeOf((*MockService)(nil).GetWeatherByLocation), ctx, location)
}
